### ISSUE TITLE
NoMethodError (undefined method `bytesize' for nil:NilClass)

### ISSUE THREAD

**Issue by marktran** [Mashape/analytics-agent-ruby#3]
Having issues getting the Ruby agent (1.0.3) running on a Rails 4.1.11 app.

I've included the middleware in `config/environments/staging.rb`:

```
config.middleware.use 'MashapeAnalytics::Frameworks::Rails', service_token: Rails.application.secrets.mashape_analytics_key, environment: 'staging'
```

Stacktrace:

```
2015-07-08_04:45:18.29586 [e28bf83a-0340-4a22-a2c3-bfe018a96e56] [127.0.0.1] 
2015-07-08_04:45:18.29597 NoMethodError (undefined method `bytesize' for nil:NilClass):
2015-07-08_04:45:18.29601   mashape-analytics (1.0.3) lib/mashape-analytics/frameworks/rack.rb:85:in `block in request_header_size'
2015-07-08_04:45:18.29605   mashape-analytics (1.0.3) lib/mashape-analytics/frameworks/rack.rb:85:in `each'
2015-07-08_04:45:18.29608   mashape-analytics (1.0.3) lib/mashape-analytics/frameworks/rack.rb:85:in `map'
2015-07-08_04:45:18.29612   mashape-analytics (1.0.3) lib/mashape-analytics/frameworks/rack.rb:85:in `request_header_size'
2015-07-08_04:45:18.29616   mashape-analytics (1.0.3) lib/mashape-analytics/frameworks/rack.rb:162:in `record_alf'
2015-07-08_04:45:18.29622   mashape-analytics (1.0.3) lib/mashape-analytics/frameworks/rack.rb:41:in `call'
2015-07-08_04:45:18.29627   rack (1.5.5) lib/rack/etag.rb:23:in `call'
2015-07-08_04:45:18.29632   rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
2015-07-08_04:45:18.29636   rack (1.5.5) lib/rack/head.rb:11:in `call'
2015-07-08_04:45:18.29640   actionpack (4.1.11) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2015-07-08_04:45:18.29645   actionpack (4.1.11) lib/action_dispatch/middleware/flash.rb:254:in `call'
2015-07-08_04:45:18.29649   rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
2015-07-08_04:45:18.29653   rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
2015-07-08_04:45:18.29658   actionpack (4.1.11) lib/action_dispatch/middleware/cookies.rb:562:in `call'
2015-07-08_04:45:18.29661   activerecord (4.1.11) lib/active_record/query_cache.rb:36:in `call'
2015-07-08_04:45:18.29665   activerecord (4.1.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
2015-07-08_04:45:18.29669   actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2015-07-08_04:45:18.29672   activesupport (4.1.11) lib/active_support/callbacks.rb:82:in `run_callbacks'
2015-07-08_04:45:18.29676   actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2015-07-08_04:45:18.29679   actionpack (4.1.11) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
2015-07-08_04:45:18.29683   bugsnag (2.8.8) lib/bugsnag/rack.rb:33:in `call'
2015-07-08_04:45:18.29687   actionpack (4.1.11) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2015-07-08_04:45:18.29690   actionpack (4.1.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2015-07-08_04:45:18.29694   lograge (0.3.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
2015-07-08_04:45:18.29697   railties (4.1.11) lib/rails/rack/logger.rb:20:in `block in call'
2015-07-08_04:45:18.29701   activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `block in tagged'
2015-07-08_04:45:18.29706   activesupport (4.1.11) lib/active_support/tagged_logging.rb:26:in `tagged'
2015-07-08_04:45:18.29709   activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `tagged'
2015-07-08_04:45:18.29713   railties (4.1.11) lib/rails/rack/logger.rb:20:in `call'
2015-07-08_04:45:18.29716   actionpack (4.1.11) lib/action_dispatch/middleware/request_id.rb:21:in `call'
2015-07-08_04:45:18.29720   rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
2015-07-08_04:45:18.29724   rack (1.5.5) lib/rack/runtime.rb:17:in `call'
2015-07-08_04:45:18.29727   activesupport (4.1.11) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
2015-07-08_04:45:18.29731   actionpack (4.1.11) lib/action_dispatch/middleware/static.rb:84:in `call'
2015-07-08_04:45:18.29735   rack-cors (0.3.1) lib/rack/cors.rb:72:in `call'
2015-07-08_04:45:18.29738   rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
2015-07-08_04:45:18.29742   railties (4.1.11) lib/rails/engine.rb:514:in `call'
2015-07-08_04:45:18.29745   railties (4.1.11) lib/rails/application.rb:144:in `call'
2015-07-08_04:45:18.29749   puma (2.11.1) lib/puma/configuration.rb:82:in `call'
2015-07-08_04:45:18.29753   puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
2015-07-08_04:45:18.29756   puma (2.11.1) lib/puma/server.rb:375:in `process_client'
2015-07-08_04:45:18.29760   puma (2.11.1) lib/puma/server.rb:262:in `block in run'
2015-07-08_04:45:18.29764   puma (2.11.1) lib/puma/thread_pool.rb:104:in `call'
2015-07-08_04:45:18.29768   puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by kennethklee** [comment]
@marktran released 1.0.4 that should have fixed this bug. Thanks for reporting.
